import type { AssetCategory } from "./asset-types";

interface AssetRecord {
  filename: string;
  category: AssetCategory;
  assetId: string;
}

function sanitizeLuaKey(filename: string): string {
  const stem = filename.replace(/\.[^.]+$/, "");
  return stem.replace(/[-\s.]/g, "_");
}

export function generateAssetsLua(assets: AssetRecord[]): string {
  const grouped: Record<AssetCategory, AssetRecord[]> = {
    Image: [],
    Audio: [],
    Model: [],
  };

  for (const asset of assets) {
    grouped[asset.category]?.push(asset);
  }

  let output = "-- Auto-generated by Roblox Asset Uploader\n";
  output += "-- Do not edit manually\n\n";
  output += "local Assets = {\n";

  for (const category of ["Image", "Audio", "Model"] as AssetCategory[]) {
    const entries = grouped[category];
    if (entries.length === 0) continue;

    output += `    ${category} = {\n`;
    for (const entry of entries.sort((a, b) =>
      a.filename.localeCompare(b.filename)
    )) {
      const key = sanitizeLuaKey(entry.filename);
      output += `        ${key} = "rbxassetid://${entry.assetId}",\n`;
    }
    output += "    },\n";
  }

  output += "}\n\nreturn Assets\n";
  return output;
}

export function generateLockfileToml(assets: AssetRecord[]): string {
  const grouped: Record<AssetCategory, AssetRecord[]> = {
    Image: [],
    Audio: [],
    Model: [],
  };

  for (const asset of assets) {
    grouped[asset.category]?.push(asset);
  }

  let output = "[assets]\n";

  for (const category of ["Image", "Audio", "Model"] as AssetCategory[]) {
    const entries = grouped[category];
    if (entries.length === 0) continue;

    output += `\n[assets.${category}]\n`;
    for (const entry of entries.sort((a, b) =>
      a.filename.localeCompare(b.filename)
    )) {
      output += `"${entry.filename}" = ${entry.assetId}\n`;
    }
  }

  return output;
}
