use crate::lockfile::LockFile;
use std::path::Path;

pub fn generate_assets_lua(lockfile: &LockFile) -> String {
    let mut output = String::new();
    output.push_str("-- Auto-generated by Roblox Asset Uploader\n");
    output.push_str("-- Do not edit manually\n\n");
    output.push_str("local Assets = {\n");

    write_category(&mut output, "Image", &lockfile.assets.image);
    write_category(&mut output, "Audio", &lockfile.assets.audio);
    write_category(&mut output, "Model", &lockfile.assets.model);

    output.push_str("}\n\nreturn Assets\n");
    output
}

fn write_category(
    output: &mut String,
    name: &str,
    entries: &std::collections::BTreeMap<String, u64>,
) {
    if entries.is_empty() {
        return;
    }
    output.push_str(&format!("    {name} = {{\n"));
    for (filename, asset_id) in entries {
        let stem = Path::new(filename)
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or(filename)
            .replace(['-', ' ', '.'], "_");
        output.push_str(&format!(
            "        {stem} = \"rbxassetid://{asset_id}\",\n"
        ));
    }
    output.push_str("    },\n");
}

pub fn save_assets_lua(lockfile: &LockFile, path: &Path) -> Result<(), String> {
    let content = generate_assets_lua(lockfile);
    std::fs::write(path, content).map_err(|e| format!("Failed to write Assets.lua: {e}"))
}
